### ISSUE TITLE
C1 S9

### ISSUE THREAD

**Issue by hbehkamal** [hbehkamal/wp#9]
## Class
- Working with HTML
- CSS Intro
## Sample Code

``` css
html {
color:red;
}
h1 {
color: blue;
}
h1.classname {
color:#987654;
}
```
# HOMEWORK:
- Learn HTML until [lists](http://www.w3schools.com/html/html_lists.asp) in w3chools.com
- CSS Training
